config/routes.rb
Rails.application.routes.draw do

  get 'api/new'
  get 'api/:fecha1/:fecha2', to: 'api#date_between'
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'likes/:tweet_id' , to: 'likes#create', as: 'likes'
  post 'retweets/:tweet_id' , to: 'retweets#create', as: 'retweets'
  post 'api/create_tweet'


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }    
  resources :tweets do
    collection do
      post :search_tweet, as: 'search'          
    end
  end
  root to: "tweets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id            :integer          not null, primary key
#  content       :string
#  image_url     :string
#  total_like    :integer          default(0)
#  total_retweet :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :retweets    
    validates :content, presence: true
    paginates_per 50
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController   

  def index
    @q = Tweet.ransack(params[:q])
    @tweets = Tweet.order(:created_at).reverse_order.page params[:page]
    @tweet = Tweet.new

      
     if params.has_key? :search
       @tweets = @tweets.where("content LIKE '%#{params[:search]}%'")
     else
       @tweets 
     end
  end

  def search_tweet
    @q = Tweet.ransack(params[:q])          
    @tweet_search = @q.result(distinct: true)    
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save!
      flash[:notice] = "Fake Tweet creado con exito."      
    else
      flash[:notice] = "Fake Tweet  no pudo ser creado."      
    end    
    redirect_to root_path    
  end

  def show    
    @tweet = Tweet.find(params[:id])
  end

  def edit
  end

 

  def update
  end

  def destroy
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, :image_url)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def render_with_hashtags(content)
        content_words = content.split(" ")
        content_with_links = content_words.map do |word| 
          if word.include?("#")                    
            link_to word, tweets_path(search: word)
          else
            word
          end
        end    
        content_with_links.join(" ")
    end
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, class:"container my-4 shadow p-3 mb-5 bg-white rounded" do |f| %>
    <%= f.label :content, "contenido del tweet", class:"h2"%>
    <%= f.text_area :content, class:"form-control"%>
    <br>
    <%= f.label :image_url, "url de la imagen", class:"h2"%>
    <%= f.text_field :image_url, class:"form-control"%>
    <%= f.submit "Create" , class:"btn btn-outline-primary my-3"%>    
<% end %> 

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
    <% if current_user %>
    <div class="container my-4">
        <%= render  "form" %>
        <%= search_form_for @q, url: search_tweets_path, class:"form-inline", method: :post do |f| %>
        <%= f.search_field :content_cont, class:"form-control my-3" %>
        <br>
        <%= f.submit "buscar", class:"btn btn-primary mx-3" %>
        <%end%>
    </div>


    </div>
    <% @tweets.each do |tweet|%>
    <div class="container my-4 shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-1 container-fluid my-5">
                <%= image_tag  "#{tweet.user.image_url}", class:" rounded-circle img-thumbnail" %>
            </div>
            <div class="col container-fluid">
                <div class="card container my-3" style="width: 50rem;">
                    <%= image_tag  "#{tweet.image_url}", class: "card-img-top m-2" %>
                    <div class="card-body">
                        <p class="card-text"><%= render_with_hashtags(tweet.content).html_safe%></p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <%= link_to  "#{tweet.total_like} Like", likes_path(tweet.id), method: :post, class:"btn btn-primary"%>
                                <%= link_to  "#{tweet.total_retweet} Retweet", retweets_path(tweet.id), method: :post, class:"btn btn-primary"%>

                            </li>
                            <li class="list-group-item p-3">
                                <%= link_to  distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class:"btn btn-light" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%end%>
    <%else%>
    
    <% @tweets.each do |tweet|%>
    <div class="container my-4 shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-1 container-fluid my-5">       
            </div>
            <div class="col container-fluid">
                <div class="card container my-3" style="width: 50rem;">
                    <%= image_tag  "#{tweet.image_url}", class: "card-img-top m-2" %>
                    <div class="card-body">
                        <p class="card-text"><%= tweet.content%></p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item p-3">
                                <%= link_to  distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class:"btn btn-light" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%end%>
    <%end%>

    <%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1 class="my-4">Crear Tweet</h1>
<div>
<%= render  "form"%>
</div>

app/views/tweets/search_tweet.html.erb
<%@tweet_search.each do |tweet|%>
    <div class="container my-4 shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-1 container-fluid my-5">                
                <%= image_tag  "#{tweet.user.image_url}", class:" rounded-circle img-thumbnail" %>
            </div>
            <div class="col container-fluid">
                <div class="card container my-3" style="width: 50rem;">
                    <%= image_tag  "#{tweet.image_url}", class: "card-img-top m-2" %>
                    <div class="card-body">
                        <p class="card-text"><%= tweet.content%></p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">  
                                <%= link_to  "#{tweet.total_like} Like", likes_path(tweet.id), method: :post, class:"btn btn-primary"%>
                                <%= link_to  "#{tweet.total_retweet} Retweet", retweets_path(tweet.id), method: :post, class:"btn btn-primary"%>
                                
                            </li>
                            <li class="list-group-item p-3">
                                <%= link_to  distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class:"btn btn-light" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<%end%>

app/views/tweets/show.html.erb
<h1 class="my-3">Tweet</h1>

<div class="container my-4 shadow p-3 mb-5 bg-white rounded">
    <div class="row">
        <div class="col-1 container-fluid my-5">
            <%= image_tag  "#{@tweet.user.image_url}", class:" rounded-circle img-thumbnail" %>

        </div>
        <div class="col container-fluid">
            <div class="card container my-3" style="width: 50rem;">
                <%= image_tag  "#{@tweet.image_url}", class: "card-img-top m-2" %>
                <div class="card-body">
                    <p class="card-text"><%= @tweet.content%></p>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <%= link_to  "#{@tweet.total_like} Like", likes_path(@tweet.id), method: :post, class:"btn btn-primary"%>
                            <%= link_to  "#{@tweet.total_retweet} Retweet", retweets_path(@tweet.id), method: :post, class:"btn btn-primary"%>
                        </li>
                        <li>
                            <p>Hace: <%=@tweet.created_at.strftime("%Y-%m-%d")%> </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<%= link_to  "Volver", tweets_path, class:"btn btn-primary my-5" %>


    
    

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>