config/routes.rb
Rails.application.routes.draw do

  get 'api/new'
  get 'api/:fecha1/:fecha2', to: 'api#date_between'
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'likes/:tweet_id' , to: 'likes#create', as: 'likes'
  post 'retweets/:tweet_id' , to: 'retweets#create', as: 'retweets'
  post 'api/create_tweet'


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }    
  resources :tweets do
    collection do
      post :search_tweet, as: 'search'          
    end
  end
  root to: "tweets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<% if current_user %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to  " Twitter ", tweets_path, class:"mx-5" %>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <%= link_to  "Crear tweet", new_tweet_path, method: :get, class: "nav-item nav-link" %>
            <%= link_to  "Cerrar session", destroy_user_session_path, method: :delete,  class: "nav-item nav-link" %>
            <%= link_to  "Mi perfil", edit_user_registration_path, class: "nav-item nav-link" %>
        </div>
    </div>        
</nav>
<%else%>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to  " <' Twitter '>", tweets_path, class:"mx-5" %>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <%= link_to  "Registrarse", new_user_registration_path, class: "nav-item nav-link" %>
            <%= link_to  "Iniciar seccion", new_user_session_path, class: "nav-item nav-link" %>
        </div>
    </div>
</nav>
<%end%>